import {Team} from './team.model';

export const europe: Team[] = [
    { name: "Real Madrid CF", country: "ESP" },
    { name: "FC Barcelona", country: "ESP" },
    { name: "FC Bayern München", country: "GER" },
    { name: "Manchester United", country: "ENG" },
    { name: "Chelsea FC", country: "ENG" },
    { name: "Atletico de Madrid", country: "ESP" },
    { name: "Liverpool FC", country: "ENG" },
    { name: "Arsenal FC", country: "ENG" },
    { name: "FC Juventus", country: "ITA" },
    { name: "FC Porto", country: "POR" },
    { name: "Sevilla CF", country: "ESP" },
    { name: "SL Benfica", country: "POR" },
    { name: "Manchester City", country: "ENG" },
    { name: "Tottenham Hotspur FC", country: "ENG" },
    { name: "Paris Saint Germain", country: "FRA" },
    { name: "BV Borussia Dortmund", country: "GER" },
    { name: "Olympique Lyonnais", country: "FRA" },
    { name: "AS Roma", country: "ITA" },
    { name: "Valencia CF", country: "ESP" },
    { name: "FC Shakhtar Donetsk", country: "UKR" },
    { name: "Ajax Amsterdam", country: "NED" },
    { name: "SSC Napoli", country: "ITA" },
    { name: "FC Internazionale", country: "ITA" },
    { name: "FC Zenit St.Petersburg", country: "RUS" },
    { name: "Milan AC", country: "ITA" },
    { name: "Sporting Club Portugal", country: "POR" },
    { name: "Dynamo Kiev", country: "UKR" },
    { name: "Villarreal CF", country: "ESP" },
    { name: "FC Schalke 04", country: "GER" },
    { name: "TSV Bayer 04 Leverkusen", country: "GER" },
    { name: "CSKA Moskva", country: "RUS" },
    { name: "Olympique de Marseille", country: "FRA" },
    { name: "SS Lazio", country: "ITA" },
    { name: "PSV Eindhoven", country: "NED" },
    { name: "FC Basel 1893", country: "SUI" },
    { name: "AS Monaco", country: "FRA" },
    { name: "Besiktas JK", country: "TUR" },
    { name: "RB Salzburg", country: "AUT" },
    { name: "Olympiakos Pireus FC", country: "GRE" },
    { name: "Athletic Club Bilbao", country: "ESP" },
    { name: "Sporting Braga", country: "POR" },
    { name: "RSC Anderlecht", country: "BEL" },
    { name: "Celtic FC Glasgow", country: "SCO" },
    { name: "Galatasaray SK", country: "TUR" },
    { name: "RasenBallsport Leipzig", country: "GER" },
    { name: "Eintracht Frankfurt", country: "GER" },
    { name: "Fenerbahce SK", country: "TUR" },
    { name: "FK Krasnodar", country: "RUS" },
    { name: "Lokomotiv Moskva", country: "RUS" },
    { name: "Club Brugge KV", country: "BEL" },
    { name: "FC Viktoria Plzen", country: "CZE" },
    { name: "KRC Genk", country: "BEL" },
    { name: "Borussia Mönchengladbach", country: "GER" },
    { name: "AZ Alkmaar", country: "NED" },
    { name: "Fiorentina AC", country: "ITA" },
    { name: "NK Dinamo Zagreb", country: "CRO" },
    { name: "Atalanta Bergamo", country: "ITA" },
    { name: "FC Kobenhavn", country: "DEN" },
    { name: "Feyenoord Rotterdam", country: "NED" },
    { name: "Everton FC", country: "ENG" },
    { name: "VfL Wolfsburg", country: "GER" },
    { name: "AS Saint Etienne", country: "FRA" },
    { name: "Spartak Moskva FC", country: "RUS" },
    { name: "Real Betis Balompie", country: "ESP" },
    { name: "Real Sociedad", country: "ESP" },
    { name: "SK Slavia Praha", country: "CZE" },
    { name: "APOEL Nicosie", country: "CYP" },
    { name: "Girondins de Bordeaux", country: "FRA" },
    { name: "LOSC Lille", country: "FRA" },
    { name: "Stade Rennais", country: "FRA" },
    { name: "Young Boys Bern", country: "SUI" },
    { name: "1899 Hoffenheim", country: "GER" },
    { name: "FCSB Bucarest", country: "ROM" },
    { name: "Ludogorets Razgrad", country: "BUL" },
    { name: "Celta Vigo", country: "ESP" },
    { name: "Standard de Liège", country: "BEL" },
    { name: "Montpellier HSC", country: "FRA" },
    { name: "Leicester City", country: "ENG" },
    { name: "PAOK Salonique", country: "GRE" },
    { name: "OGC Nice", country: "FRA" },
    { name: "AC Sparta Praha", country: "CZE" },
    { name: "RCD Espanyol", country: "ESP" },
    { name: "Getafe CF", country: "ESP" },
    { name: "KAA Gent", country: "BEL" },
    { name: "FK Astana", country: "KAZ" },
    { name: "AEK Athens", country: "GRE" },
    { name: "FK Crevna Zvezda", country: "SRB" },
    { name: "Torino FC", country: "ITA" },
    { name: "AFC Bournemouth", country: "ENG" },
    { name: "Udinese Calcio", country: "ITA" },
    { name: "Garabag Agdam", country: "AZE" },
    { name: "Vitoria Guimaraes", country: "POR" },
    { name: "Malmö FF", country: "SWE" },
    { name: "SV Werder Bremen", country: "GER" },
    { name: "SD Eibar", country: "ESP" },
    { name: "BATE Borisov", country: "BLR" },
    { name: "UC Sampdoria", country: "ITA" },
    { name: "Rapid Wien", country: "AUT" },
    { name: "West Ham United FC", country: "ENG" },
    { name: "FK Partizan Belgrade", country: "SRB" },
    { name: "Hertha BSC Berlin", country: "GER" },
    { name: "Deportivo Alaves", country: "ESP" },
    { name: "NK Maribor", country: "SLO" },
    { name: "Maccabi Tel Aviv FC", country: "ISR" },
    { name: "Zorja Lugansk", country: "UKR" },
    { name: "Southampton FC", country: "ENG" },
    { name: "UD Levante", country: "ESP" },
    { name: "Apollon Limassol", country: "CYP" },
    { name: "Rosenborg BK", country: "NOR" },
    { name: "Crystal Palace", country: "ENG" },
    { name: "Panathinaikos FC", country: "GRE" },
    { name: "FSV Mainz 05", country: "GER" },
    { name: "Legia Varsovie", country: "POL" },
    { name: "Rio Ave", country: "POR" },
    { name: "US Sassuolo", country: "ITA" },
    { name: "Newcastle United", country: "ENG" },
    { name: "Vitesse Arnhem", country: "NED" },
    { name: "FC Zurich", country: "SUI" },
    { name: "Rangers FC", country: "SCO" },
    { name: "FC Bologna", country: "ITA" },
    { name: "Istanbul Basaksehir", country: "TUR" },
    { name: "CD Leganes", country: "ESP" },
    { name: "Malaga CF", country: "ESP" },
    { name: "Watford FC", country: "ENG" },
    { name: "FK Rostov", country: "RUS" },
    { name: "Moreirense FC", country: "POR" },
    { name: "FC Rubin Kazan", country: "RUS" },
    { name: "FC Augsburg", country: "GER" },
    { name: "CS Maritimo", country: "POR" },
    { name: "Vorskla Poltava", country: "UKR" },
    { name: "Rayo Vallecano", country: "ESP" },
    { name: "FC Nantes Atlantique", country: "FRA" },
    { name: "CFC Genoa 1893", country: "ITA" },
    { name: "Real Valladolid", country: "ESP" },
    { name: "SC Freiburg", country: "GER" },
    { name: "Wolwerhampton Wanderers", country: "ENG" },
    { name: "FC Utrecht", country: "NED" },
    { name: "FC Dnipro", country: "UKR" },
    { name: "Swansea City", country: "ENG" },
    { name: "Cagliari Calcio", country: "ITA" },
    { name: "Stade de Reims", country: "FRA" },
    { name: "HNK Rijeka", country: "CRO" },
    { name: "1.FC Köln", country: "GER" },
    { name: "Belenenses SAD", country: "POR" },
    { name: "Boavista FC", country: "POR" },
    { name: "West Bromwich Albion", country: "ENG" },
    { name: "Stoke City", country: "ENG" },
    { name: "FK Austria Wien", country: "AUT" },
    { name: "Hamburger SV", country: "GER" },
    { name: "Hapoel Beer Sheva", country: "ISR" },
    { name: "Trabzonspor", country: "TUR" },
    { name: "VfB Stuttgart", country: "GER" },
    { name: "Aston Villa", country: "ENG" },
    { name: "AEK Larnaca", country: "CYP" },
    { name: "Burnley FC", country: "ENG" },
    { name: "Konyaspor", country: "TUR" },
    { name: "FC Empoli", country: "ITA" },
    { name: "MOL Fehervar FC", country: "HUN" },
    { name: "Deportivo La Coruna", country: "ESP" },
    { name: "Parma Calcio 1913", country: "ITA" },
    { name: "SC Heerenveen", country: "NED" },
    { name: "Racing Club Strasbourg", country: "FRA" },
    { name: "Achmat Grozny", country: "RUS" },
    { name: "Nimes Olympique", country: "FRA" },
    { name: "Toulouse FC", country: "FRA" },
    { name: "PFK Oleksandriya", country: "UKR" },
    { name: "FC Groningen", country: "NED" },
    { name: "Zulte Waregem", country: "BEL" },
    { name: "Heracles Almelo", country: "NED" },
    { name: "FC Midtjylland", country: "DEN" },
    { name: "SCO Angers", country: "FRA" },
    { name: "Fulham FC", country: "ENG" },
    { name: "Cardiff City FC", country: "ENG" },
    { name: "FK Jablonec", country: "CZE" },
    { name: "SK Slovan Bratislava", country: "SVK" },
    { name: "CFR Cluj", country: "ROM" },
    { name: "Pacos de Ferreira", country: "POR" },
    { name: "FK Ural", country: "RUS" },
    { name: "SPAL Ferrara", country: "ITA" },
    { name: "Fortuna Düsseldorf", country: "GER" },
    { name: "Vitoria Setubal", country: "POR" },
    { name: "ADO Den Haag", country: "NED" },
    { name: "Sunderland FC", country: "ENG" },
    { name: "SD Huesca", country: "ESP" },
    { name: "FC Dynamo Moskva", country: "RUS" },
    { name: "Brighton & Hove Albion", country: "ENG" },
    { name: "FC Lugano", country: "SUI" },
    { name: "Hannover 96", country: "GER" },
    { name: "Portimonense SC", country: "POR" },
    { name: "Arsenal Tula", country: "RUS" },
    { name: "EA Guingamp", country: "FRA" },
    { name: "CD Tondela", country: "POR" },
    { name: "FC Twente Enschede", country: "NED" },
    { name: "Spartak Trnava", country: "SVK" },
    { name: "CD Santa Clara", country: "POR" },
    { name: "UD Las Palmas", country: "ESP" },
    { name: "PEC Zwolle", country: "NED" },
    { name: "Astra Giurgiu", country: "ROM" },
    { name: "CD Nacional", country: "POR" },
    { name: "Vardar Skopje", country: "MKD" },
    { name: "Girona CF", country: "ESP" },
    { name: "Oestersunds FK", country: "SWE" },
    { name: "Dijon FCO", country: "FRA" },
    { name: "SM Caen", country: "FRA" },
    { name: "CA Osasuna", country: "ESP" },
    { name: "Willem II Tillburg", country: "NED" },
    { name: "Skenderbeu Korce", country: "ALB" },
    { name: "Sarpsborg 08 FF", country: "NOR" },
    { name: "GD Chaves", country: "POR" },
    { name: "Chievo Verona", country: "ITA" },
    { name: "AIK Solna", country: "SWE" },
    { name: "Granada CF", country: "ESP" },
    { name: "Gazovik Orenburg", country: "RUS" },
    { name: "PFC Levski Sofia", country: "BUL" },
    { name: "Deportivo Aves", country: "POR" },
    { name: "FC Slovan Liberec", country: "CZE" },
    { name: "F91 Dudelange", country: "LUX" },
    { name: "Norwich City", country: "ENG" },
    { name: "Akhisar Belediyespor", country: "TUR" },
    { name: "SC Amiens", country: "FRA" },
    { name: "Sheriff Tiraspol", country: "MDA" },
    { name: "GD Estoril", country: "POR" },
    { name: "FK Ufa", country: "RUS" },
    { name: "Asteras Tripolis", country: "GRE" },
    { name: "FK Mariupol", country: "UKR" },
    { name: "US Palermo", country: "ITA" },
    { name: "Huddersfield Town", country: "ENG" },
    { name: "Molde FK", country: "NOR" },
    { name: "Royal Antwerp FC", country: "BEL" },
    { name: "FC Lorient", country: "FRA" },
    { name: "RSC Charleroi", country: "BEL" },
    { name: "Shkendija Tetovo", country: "MKD" },
    { name: "HJK Helsinki", country: "FIN" },
    { name: "Atromitos FC", country: "GRE" },
    { name: "FC Sion", country: "SUI" },
    { name: "Olimpija Ljubljana", country: "SLO" },
    { name: "Middlesbrough FC", country: "ENG" },
    { name: "Frosinone Calcio", country: "ITA" },
    { name: "PFC CSKA Sofia", country: "BUL" },
    { name: "Hellas Verona FC", country: "ITA" },
    { name: "Lech Poznan", country: "POL" },
    { name: "Sporting Gijon", country: "ESP" },
    { name: "FC Metz", country: "FRA" },
    { name: "Gabala FK", country: "AZE" },
    { name: "KV Kortrijk", country: "BEL" },
    { name: "Antalyaspor", country: "TUR" },
    { name: "Krylia Sowjetow Samara", country: "RUS" },
    { name: "VVV Venlo", country: "NED" },
    { name: "Ferencvarosi TC", country: "HUN" },
    { name: "Kasimpasa", country: "TUR" },
    { name: "Osmanlispor FK Ankara", country: "TUR" },
    { name: "Sivasspor", country: "TUR" },
    { name: "Olimpik Donetsk", country: "UKR" },
    { name: "Brondby IF", country: "DEN" },
    { name: "FC Zlin", country: "CZE" },
    { name: "Aberdeen FC", country: "SCO" },
    { name: "Dundalk FC", country: "IRL" },
    { name: "Excelsior Rotterdam", country: "NED" },
    { name: "Desna Tchernihiv", country: "UKR" },
    { name: "FK Lviv", country: "UKR" },
    { name: "K. Sint-Truidense VV", country: "BEL" },
    { name: "Radnicki Nis", country: "SRB" },
    { name: "Yeni Malatyaspor", country: "TUR" },
    { name: "FC Arouca", country: "POR" },
    { name: "Karparty Lviv", country: "UKR" },
    { name: "AEL Limassol", country: "CYP" },
    { name: "Hull City", country: "ENG" },
    { name: "FC Luzern", country: "SUI" },
    { name: "HNK Hajduk Split", country: "CRO" },
    { name: "Amkar Perm", country: "RUS" },
    { name: "ES Troyes AC", country: "FRA" },
    { name: "FC Crotone", country: "ITA" },
    { name: "Alanyaspor", country: "TUR" },
    { name: "FC Thun", country: "SUI" },
    { name: "CD Feirense", country: "POR" },
    { name: "Norrkopings IFK", country: "SWE" },
    { name: "Wolfsberger AC", country: "AUT" },
    { name: "FC Emmen", country: "NED" },
    { name: "Kayserispor", country: "TUR" },
    { name: "Dinamo Minsk", country: "BLR" },
    { name: "KV Oostende", country: "BEL" },
    { name: "Stade Brestois", country: "FRA" },
    { name: "LASK", country: "AUT" },
    { name: "FC Sankt Gallen", country: "SUI" },
    { name: "MSK Zilina", country: "SVK" },
    { name: "Lechia Gdansk", country: "POL" },
    { name: "Jagiellonia Bialystok", country: "POL" },
    { name: "Maccabi Haifa FC", country: "ISR" },
    { name: "Caykur Rizespor", country: "TUR" },
    { name: "Sturm Graz", country: "AUT" },
    { name: "Royal Excel Mouscron", country: "BEL" },
    { name: "Neftchi Baku", country: "AZE" },
    { name: "Panionios", country: "GRE" },
    { name: "Derby County FC", country: "ENG" },
    { name: "1.FC Nurnberg", country: "GER" },
    { name: "Fortuna Sittard", country: "NED" },
    { name: "Academica Coimbra", country: "POR" },
    { name: "KV Mechelen", country: "BEL" },
    { name: "Djurgardens IF", country: "SWE" },
    { name: "SV Darmstadt 98", country: "GER" },
    { name: "Bursaspor", country: "TUR" },
    { name: "NK Domzale", country: "SLO" },
    { name: "Sheffield United", country: "ENG" },
    { name: "DAC Dunajska Streda", country: "SVK" },
    { name: "Cukaricki Belgrade", country: "SRB" },
    { name: "Piast Gliwice", country: "POL" },
    { name: "BK Hacken", country: "SWE" },
    { name: "AS Trencin", country: "SVK" },
    { name: "NK Osijek", country: "CRO" },
    { name: "SK Sigma Olomouc", country: "CZE" },
    { name: "Kuban Krasnodar", country: "RUS" },
    { name: "Brescia Calcio", country: "ITA" },
    { name: "Universitatea Craiova", country: "ROM" },
    { name: "1.FC Union Berlin", country: "GER" },
    { name: "Genclerbirligi SK", country: "TUR" },
    { name: "FC Viitorul Constanta", country: "ROM" },
    { name: "Goztepe Izmir", country: "TUR" },
    { name: "Ilves Tampere", country: "FIN" },
    { name: "1.FC Union Berlin", country: "GER" },
    { name: "FC Ingolstadt 04", country: "GER" },
    { name: "Benevento Calcio", country: "ITA" },
    { name: "Anorthosis Famagusta", country: "CYP" },
    { name: "Real Mallorca", country: "ESP" },
    { name: "Albacete Balompie", country: "ESP" },
    { name: "Hammarby IF", country: "SWE" },
    { name: "MKE Ankaragucu", country: "TUR" },
    { name: "Cadiz CF", country: "ESP" },
    { name: "AO Xanthi", country: "GRE" },
    { name: "Anzhi Makhachkala", country: "RUS" },
    { name: "FC Famalicao", country: "POR" },
    { name: "UD Almeria", country: "ESP" },
    { name: "Aalborg BK", country: "DEN" },
    { name: "Beroe Stara Zagora", country: "BUL" },
    { name: "Wisla Krakow", country: "POL" },
    { name: "US Lecce", country: "ITA" },
    { name: "Cracovia Krakow", country: "POL" },
    { name: "Aris Salonique", country: "GRE" },
    { name: "Kilmarnock FC", country: "SCO" },
    { name: "Wolyn Luzk", country: "UKR" },
    { name: "NEC Nijmegen", country: "NED" },
    { name: "De Graafschap Doetinchem", country: "NED" },
    { name: "Leeds United", country: "ENG" },
    { name: "Roda JC", country: "NED" },
    { name: "Paris FC", country: "FRA" },
    { name: "Debrecen VSC", country: "HUN" },
    { name: "FC Dinamo Bucuresti", country: "ROM" },
    { name: "Zaglebie Lubin", country: "POL" },
    { name: "Mlada Boleslav", country: "CZE" },
    { name: "SC Paderborn 07", country: "GER" },
    { name: "Racing Club de Lens", country: "FRA" },
    { name: "FC Nordsjaelland", country: "DEN" },
    { name: "Hibernian Edinburgh", country: "SCO" },
    { name: "Pandurii Targu Jiu", country: "ROM" },
    { name: "Le Havre AC", country: "FRA" },
    { name: "Pogon Szczecin", country: "POL" },
    { name: "Kairat Almaty", country: "KAZ" },
    { name: "Kuopio PS", country: "FIN" },
    { name: "Suduva Marijampole", country: "LTU" },
    { name: "Real Oviedo", country: "ESP" },
    { name: "MFK Ruzomberok", country: "SVK" },
    { name: "Panetolikos Agrinio", country: "GRE" },
    { name: "1.FC Heidenheim", country: "GER" },
    { name: "Odds BK Skien", country: "NOR" },
    { name: "Beitar Jerusalem", country: "ISR" },
    { name: "Seinajoen JK", country: "FIN" },
    { name: "Esbjerg FB", country: "DEN" },
    { name: "FC Penafiel", country: "POR" },
    { name: "Torpedo Kutaisi", country: "GEO" },
    { name: "Cambuur Leeuwarden", country: "NED" },
    { name: "KAS Eupen", country: "BEL" },
    { name: "Real Zaragoza", country: "ESP" },
    { name: "Neuchatel Xamax FCS", country: "SUI" },
    { name: "Chernomorets Odessa", country: "UKR" },
    { name: "Waasland Beveren", country: "BEL" },
    { name: "Delfino Pescara 1936", country: "ITA" },
    { name: "SK Brann Bergen", country: "NOR" },
    { name: "AS Nancy Lorraine", country: "FRA" },
    { name: "Arsenal Kiev", country: "UKR" },
    { name: "Kolos Kovalivka", country: "UKR" },
    { name: "FK Stal Kamjanske", country: "UKR" },
    { name: "Sheffield Wednesday", country: "ENG" },
    { name: "IFK Mariehamn", country: "FIN" },
    { name: "FK Bodo/Glimt", country: "NOR" },
    { name: "Honved Budapest", country: "HUN" },
    { name: "Sparta Rotterdam", country: "NED" },
    { name: "FC Lahti", country: "FIN" },
    { name: "AS Cittadella", country: "ITA" },
    { name: "FC Banik Ostrava", country: "CZE" },
    { name: "Slask Wroclaw", country: "POL" },
    { name: "Hapoel Haifa", country: "ISR" },
    { name: "Cercle Brugge", country: "BEL" },
    { name: "SC Dnipro-1", country: "UKR" },
    { name: "PAS Ioannina", country: "GRE" },
    { name: "HNK Gorica", country: "CRO" },
    { name: "Korona Kielce", country: "POL" },
    { name: "Vojvodina Novi Sad", country: "SRB" },
    { name: "Holstein Kiel", country: "GER" },
    { name: "Bristol City", country: "ENG" },
    { name: "Elfsborg Boras", country: "SWE" },
    { name: "Inter Turku", country: "FIN" },
    { name: "APO Levadiakos", country: "GRE" },
    { name: "AC Perugia", country: "ITA" },
    { name: "Ujpest Budapest", country: "HUN" },
    { name: "IFK Göteborg", country: "SWE" },
    { name: "Clermont Foot", country: "FRA" },
    { name: "AS Lamia", country: "GRE" },
    { name: "FC Botosani", country: "ROM" },
    { name: "Jahn Regensburg", country: "GER" },
    { name: "Kristiansund BK", country: "NOR" },
    { name: "Cherno More Varna", country: "BUL" },
    { name: "Mladost Lucani", country: "SRB" },
    { name: "Ironi Kiryat Shmona", country: "ISR" },
    { name: "Botev Plovdiv", country: "BUL" },
    { name: "NS Mura", country: "SLO" },
    { name: "Sporting Covilha", country: "POR" },
    { name: "Dundee United", country: "SCO" },
    { name: "KSC Lokeren OV", country: "BEL" },
    { name: "Spezia Calcio", country: "ITA" },
    { name: "Brentford FC", country: "ENG" },
    { name: "Hapoel Tel Aviv FC", country: "ISR" },
    { name: "Eintracht Braunschweig", country: "GER" },
    { name: "NK Celje", country: "SLO" },
    { name: "St.Johnstone FC", country: "SCO" },
    { name: "Arminia Bielefeld", country: "GER" },
    { name: "Petrolul Ploiesti", country: "ROM" },
    { name: "Honka Espoo", country: "FIN" },
    { name: "RKC Waalwijk", country: "NED" },
    { name: "Gornik Zabrze", country: "POL" },
    { name: "Elche CF", country: "ESP" },
    { name: "Valerenga IF", country: "NOR" },
    { name: "SKN St.Poelten", country: "AUT" },
    { name: "Vereya Stara Zagora", country: "BUL" },
    { name: "FC St-Pauli", country: "GER" },
    { name: "C.S.M.S. Iasi", country: "ROM" },
    { name: "FC Chambly Oise", country: "FRA" },
    { name: "Birmingham City FC", country: "ENG" },
    { name: "Karlsruher SC", country: "GER" },
    { name: "Preston North End", country: "ENG" },
    { name: "Etar Veliko Tarnovo", country: "BUL" },
    { name: "Hapoel Netanya", country: "ISR" },
    { name: "FK Tambov", country: "RUS" },
    { name: "Omonia Nicosie", country: "CYP" },
    { name: "Odense BK", country: "DEN" },
    { name: "Nottingham Forest", country: "ENG" },
    { name: "Lokomotiv Sofia", country: "BUL" },
    { name: "Erzgebirge Aue", country: "GER" },
    { name: "Servette Geneve", country: "SUI" },
    { name: "Gil Vicente FC", country: "POR" },
    { name: "Eskisehirspor", country: "TUR" },
    { name: "Wigan Athletic", country: "ENG" },
    { name: "Academico Viseu", country: "POR" },
    { name: "Lokomotiva Zagreb", country: "CRO" },
    { name: "Bnei Yehuda", country: "ISR" },
    { name: "Millwall", country: "ENG" },
    { name: "FC Dinamo Tbilisi", country: "GEO" },
    { name: "US Cremonese", country: "ITA" },
    { name: "Ross County", country: "SCO" },
    { name: "Gaz Metan Medias", country: "ROM" },
    { name: "Diosgyori VTK", country: "HUN" },
    { name: "FK Teplice", country: "CZE" },
    { name: "AE Larisa", country: "GRE" },
    { name: "SCR Altach", country: "AUT" },
    { name: "SonderjyskE", country: "DEN" },
    { name: "Leixoes Matosinhos", country: "POR" },
    { name: "LB Chateauroux", country: "FRA" },
    { name: "Panthrakikos", country: "GRE" }
];
